spring:
  datasource:
    url: jdbc:h2:mem:db1;MODE=PostgreSQL;DB_CLOSE_ON_EXIT=FALSE
    type: com.zaxxer.hikari.HikariDataSource
    driverClassName: org.h2.Driver
    username: sa
    password:
    hikari:
      pool-name: orders.connection.pool
  jpa:
    hibernate:
      ddl-auto: create-drop
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyHbmImpl
    show-sql: true
    open-in-view: false
server:
  port: ${ORDERING_SERVICE_PORT:8084}
